# Settings for Backend (on Cloud Run).
# See https://firebase.google.com/docs/app-hosting/configure#cloud-run
runConfig:
  sessionAffinity: true # Enable Session Affinity to keep the socket on one instance
  cpuIdle: false # Ensure the CPU stays active during the socket connection
  timeoutSeconds: 3600 # Increase timeout to allow long-lived WebSockets
  minInstances: 0
  # maxInstances: 100
  # concurrency: 80
  # cpu: 1
  # memoryMiB: 512

# Environment variables and secrets.
env:
  # Configure environment variables.
  # See https://firebase.google.com/docs/app-hosting/configure#user-defined-environment

  - variable: MODE
    value: "dev"
    availability:
      - BUILD
      - RUNTIME

  - variable: SKIP_SSG
    value: "true"
    availability:
      - BUILD
      - RUNTIME

  - variable: SKIP_CSS_COMPILE
    value: "false"
    availability:
      - BUILD
      - RUNTIME

  - variable: SKIP_CLIENT_COMPILE
    value: "true"
    availability:
      - BUILD
      - RUNTIME

  - variable: SKIP_SERVER_COMPILE
    value: "true"
    availability:
      - BUILD
      - RUNTIME

  # Grant access to secrets in Cloud Secret Manager.
  # See https://firebase.google.com/docs/app-hosting/configure#secret-parameters

  - variable: JWT_SECRET_KEY
    secret: JWT_SECRET_KEY

  - variable: GOOGLE_OAUTH_CLIENT_ID
    secret: GOOGLE_OAUTH_CLIENT_ID

  - variable: GOOGLE_OAUTH_CLIENT_SECRET
    secret: GOOGLE_OAUTH_CLIENT_SECRET
